// <auto-generated />
using BooksSpring26.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BooksSpring26.Migrations
{
    [DbContext(typeof(BooksDbContext))]
    [Migration("20260115155817_createCategoryTableWithSeedData")]
    partial class createCategoryTableWithSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BooksSpring26.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Travel books",
                            Name = "Travel"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Mystery books",
                            Name = "Mystery"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Science Fiction books",
                            Name = "Science Fiction"
                        },
                        new
                        {
                            CategoryId = 4,
                            Description = "Romance books",
                            Name = "Romance"
                        },
                        new
                        {
                            CategoryId = 5,
                            Description = "Guide books",
                            Name = "Giude"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
