// <auto-generated />
using BooksSpring26.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BooksSpring26.Migrations
{
    [DbContext(typeof(BooksDbContext))]
    [Migration("20260203153743_bookClass")]
    partial class bookClass
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BooksSpring26.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Korn",
                            CategoryId = 1,
                            Description = "wow",
                            ImgUrl = "ufhwvhsvsns",
                            Price = 3.00m,
                            Title = "Into the Wild"
                        },
                        new
                        {
                            BookId = 7,
                            Author = "Helen Mercer",
                            CategoryId = 1,
                            Description = "A gripping travelogue through the harsh Sahara dunes.",
                            ImgUrl = "img_desert_winds",
                            Price = 11.00m,
                            Title = "Across the Desert Winds"
                        },
                        new
                        {
                            BookId = 8,
                            Author = "Mark Holloway",
                            CategoryId = 2,
                            Description = "A detective uncovers the truth behind a mysterious locked-room disappearance.",
                            ImgUrl = "img_vanishing_key",
                            Price = 8.90m,
                            Title = "The Vanishing Key"
                        },
                        new
                        {
                            BookId = 9,
                            Author = "Rivka Hale",
                            CategoryId = 3,
                            Description = "A sci-fi adventure across galaxies filled with ancient civilizations and hidden dangers.",
                            ImgUrl = "img_starbound",
                            Price = 16.00m,
                            Title = "Starbound Chronicles"
                        });
                });

            modelBuilder.Entity("BooksSpring26.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Travel books",
                            Name = "Travel"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Mystery books",
                            Name = "Mystery"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Science Fiction books",
                            Name = "Science Fiction"
                        },
                        new
                        {
                            CategoryId = 4,
                            Description = "Romance books",
                            Name = "Romance"
                        },
                        new
                        {
                            CategoryId = 5,
                            Description = "Guide books",
                            Name = "Guide"
                        });
                });

            modelBuilder.Entity("BooksSpring26.Models.Book", b =>
                {
                    b.HasOne("BooksSpring26.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
